server:
  port: 8081

spring:
  profiles:
    active: test

  redis:
    # Redis数据库
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200
  cache:
    redis:
      time-to-live: 1800s

ltcache:
  # 是否存储空值，默认true，防止缓存穿透
  allowNullValues: true
  # 一级缓存集合，cacheName维度
  l1CacheNameSet:
    - goods
    - pins
  # 一级缓存
  caffeine:
    # 是否自动刷新过期缓存 true 是 false 否
    autoRefreshExpireCache: false
    # 缓存刷新调度线程池的大小
    refreshPoolSize: 2
    # 缓存刷新的频率(秒)
    refreshPeriod: 10
    # 写入后过期时间(秒)
    expireAfterWrite: 180
    # 访问后过期时间(秒)
    expireAfterAccess: 180
    # 初始化大小
    initialCapacity: 1000
    # 最大缓存对象个数，超过此数量时之前放入的缓存将失效
    maximumSize: 3000
  # 二级缓存
  redis:
    # 全局过期时间，单位毫秒，默认不过期
    defaultExpiration: 300000
    # 每个cacheName的过期时间，单位毫秒，优先级比defaultExpiration高
    expires: {goods: 300000,pins: 60000}
    # 缓存更新时通知其他节点的topic名称 默认 cache:redis:caffeine:topic
    topic: cache:redis:caffeine:topic